name: Deploy to GCP VM with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: GCP_SSH_PRIVATE_KEY

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: SSH into VM
        run: |
          ssh -T arief_of_komikapecahkan@${{ secrets.GCP_VM_IP }} "echo 'Connected to VM'"

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app:latest .

      # Save the Docker image as a tar file
      - name: Save Docker image
        run: docker save my-app:latest -o my-app.tar

      # Copy the Docker image to the VM
      - name: Copy Docker image to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-action-key arief_of_komikapecahkan@${{ secrets.GCP_VM_IP }}

      # Deploy the Docker image on the VM
      - name: Deploy Docker container on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            # Load the Docker image
            docker load -i /home/${{ secrets.GCP_VM_USER }}/my-app.tar
            
            # Stop and remove any existing container
            docker stop my-app || true
            docker rm my-app || true
            
            # Run the new container
            docker run -d --name my-app -p 80:80 my-app:latest
          EOF
